### ISSUE TITLE
¿What are the accepted BBCodes?

### ISSUE THREAD

**Issue by sanslash332** [PheRum/laravel-bbcode#2]
As the title says, what are all the bbCode that this parser accepts?
Only the most basics bbCode like i, b, s, etc, or supports other bbCodes like video, youtube, title, list, etc.

Thanks :P

**Comment by OfficialGlyph** [comment]
A list can be found here: https://github.com/PheRum/laravel-bbcode/blob/master/src/BBCodeParser.php
